# Generated by Django 5.2.6 on 2025-09-30 02:10

import accounts.models
import accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        help_text="Digite apenas os números do CPF",
                        max_length=14,
                        unique=True,
                        validators=[accounts.validators.validate_cpf],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        help_text="Foto do contribuinte",
                        null=True,
                        upload_to=accounts.models.user_photo_path,
                        verbose_name="Foto de Perfil",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        help_text="Data de nascimento do contribuinte (mínimo 16 anos)",
                        validators=[accounts.validators.validate_birth_date],
                        verbose_name="Data de Nascimento",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        help_text="Telefone de contato (formato: (48) 99999-9999)",
                        max_length=15,
                        validators=[accounts.validators.validate_phone_number],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "endereco",
                    models.TextField(
                        blank=True,
                        help_text="Endereço completo em Florianópolis",
                        verbose_name="Endereço",
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True,
                        help_text="Bairro de residência em Florianópolis",
                        max_length=100,
                        validators=[
                            accounts.validators.validate_florianopolis_neighborhood
                        ],
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True,
                        help_text="CEP do endereço (formato: 88000-000)",
                        max_length=9,
                        validators=[accounts.validators.validate_cep],
                        verbose_name="CEP",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o contribuinte está ativo na plataforma",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil do Contribuinte",
                "verbose_name_plural": "Perfis dos Contribuintes",
                "ordering": ["-data_cadastro"],
            },
        ),
    ]
