# Generated by Django 5.2.6 on 2025-09-30 17:52

import alerts.models
import alerts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("enchente", "Enchente"),
                            ("deslizamento", "Deslizamento"),
                            ("incendio", "Incêndio"),
                            ("tempestade", "Tempestade"),
                            ("acidente", "Acidente"),
                            ("outros", "Outros"),
                        ],
                        help_text="Categoria do alerta",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Descrição detalhada do alerta",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "media",
                    models.FileField(
                        blank=True,
                        help_text="Foto ou vídeo do alerta (máx. 50MB)",
                        null=True,
                        upload_to=alerts.models.alert_media_path,
                        validators=[
                            alerts.validators.validate_file_size,
                            alerts.validators.validate_media_type,
                        ],
                        verbose_name="Mídia",
                    ),
                ),
                (
                    "localizacao",
                    models.CharField(
                        blank=True,
                        help_text="Localização do incidente",
                        max_length=255,
                        verbose_name="Localização",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("analisando", "Analisando"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                            ("publicado", "Publicado"),
                        ],
                        default="pendente",
                        help_text="Status da análise do alerta",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "prioridade",
                    models.IntegerField(
                        choices=[
                            (1, "Baixa"),
                            (2, "Média"),
                            (3, "Alta"),
                            (4, "Crítica"),
                        ],
                        default=1,
                        verbose_name="Prioridade",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título do post",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(
                        help_text="Conteúdo do post", verbose_name="Conteúdo"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("publicado", "Publicado"),
                            ("arquivado", "Arquivado"),
                        ],
                        default="rascunho",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(
                        default=False,
                        help_text="Post em destaque no feed",
                        verbose_name="Destaque",
                    ),
                ),
                (
                    "permite_comentarios",
                    models.BooleanField(
                        default=True, verbose_name="Permite Comentários"
                    ),
                ),
                (
                    "visualizacoes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Visualizações"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Publicação"
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        help_text="Alerta que originou este post",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="alerts.alert",
                        verbose_name="Alerta Relacionado",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        help_text="Administrador que criou o post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-data_publicacao", "-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(
                        help_text="Conteúdo do comentário", verbose_name="Comentário"
                    ),
                ),
                (
                    "aprovado",
                    models.BooleanField(
                        default=True,
                        help_text="Comentário aprovado para exibição",
                        verbose_name="Aprovado",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Comentário ao qual este é uma resposta",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="alerts.comment",
                        verbose_name="Comentário Pai",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="alerts.post",
                        verbose_name="Post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
                "ordering": ["data_criacao"],
            },
        ),
    ]
